In [135]:
from faker import Faker
import pandas as pd
from faker.providers import DynamicProvider
import datetime

fake = Faker()

In [136]:
from faker import Faker
import pandas as pd

timestamp_range = pd.date_range(start="2020-02-20",
                                end="2022-06-10")

In [137]:
customerid= DynamicProvider(
     provider_name="customerid",
     elements=[1,2,3,4,5,6,7,8,9,10])

fake.add_provider(customerid)

In [138]:
orderstatus= DynamicProvider(
     provider_name="orderstatus",
     elements=['INPROGRESS','RECIVED','DELIVERD'])

fake.add_provider(orderstatus)

In [139]:
orderid= DynamicProvider(
     provider_name="orderid",
     elements=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

fake.add_provider(orderid)

In [140]:
start_date="2020-03-20"
end_date = datetime.datetime.now()
format = "%Y-%m-%d"
start_date = datetime.datetime.strptime(start_date, format)

In [141]:
req_list=[]
order_status=['RECEIVED','INPROGRESS','DELIVERED']
for i in range(100):
    curr_timestamp= fake.date_time_between_dates(datetime_start=start_date,datetime_end=end_date)
    orderid = fake.orderid()
    customerid = fake.customerid()
    for j in range(3):
        x=[]
        x.append(orderid)
        x.append(customerid)
        x.append(curr_timestamp)
        x.append(order_status[j])
        req_list.append(x)
        curr_timestamp= curr_timestamp + datetime.timedelta(days=1);

In [142]:
df = pd.DataFrame(req_list)

In [146]:
df.shape

(300, 4)

In [144]:
df.columns=['orderid','customerid','order_status_update_timestamp','orderstatus']

In [145]:
df.to_csv('order_Details.csv',index=False)

In [147]:
import psycopg2

In [155]:
import psycopg2
#establishing the connection
try:
    conn = psycopg2.connect(
       database="postgres", user='postgres', password='{_/U{[^z>;OVTf\';', host='35.196.4.55', port= '5432')
    #Creating a cursor object using the cursor() method
except Exception as error:
    print("failed connecting to database")
cursor = conn.cursor()

In [156]:
create_table = """CREATE TABLE if not exists order_details(
               orderid bigint,
customerid bigint NOT NULL,
order_status_update_timestamp timestamp,
order_status varchar(50)
);"""

try:
    cursor.execute(create_table)
    conn.commit()
except Exception as error:
        print("failed creating table:{}",error)

In [157]:
for i in range(len(df)):
    productid = int(df['orderid'].iloc[i])
    productcode = str(df['customerid'].iloc[i])
    productname = str(df['order_status_update_timestamp'].iloc[i])
    sku = str(df['orderstatus'].iloc[i])
  
    query = ("insert into order_details (orderid,customerid, order_status_update_timestamp, order_status)"
         "values (%s, %s, %s, %s)")

    val = (productid,productcode, productname, sku)
    cursor.execute(query,val)
    conn.commit()
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299